/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.paper;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link ListDocsCursorError}
 * error.
 *
 * <p> This exception is raised by {@link
 * DbxUserPaperRequests#docsListContinue(String)}. </p>
 */
public class ListDocsCursorErrorException extends DbxApiException {
    // exception for routes:
    //     2/paper/docs/list/continue

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link
     * DbxUserPaperRequests#docsListContinue(String)}.
     */
    public final ListDocsCursorError errorValue;

    public ListDocsCursorErrorException(String routeName, String requestId, LocalizedText userMessage, ListDocsCursorError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
