/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.filerequests;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link
 * UpdateFileRequestError} error.
 *
 * <p> This exception is raised by {@link
 * DbxUserFileRequestsRequests#update(String)}. </p>
 */
public class UpdateFileRequestErrorException extends DbxApiException {
    // exception for routes:
    //     2/file_requests/update

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link DbxUserFileRequestsRequests#update(String)}.
     */
    public final UpdateFileRequestError errorValue;

    public UpdateFileRequestErrorException(String routeName, String requestId, LocalizedText userMessage, UpdateFileRequestError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
