/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.sharing;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link
 * CreateSharedLinkError} error.
 *
 * <p> This exception is raised by {@link
 * DbxUserSharingRequests#createSharedLink(String)}. </p>
 */
public class CreateSharedLinkErrorException extends DbxApiException {
    // exception for routes:
    //     2/sharing/create_shared_link

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link
     * DbxUserSharingRequests#createSharedLink(String)}.
     */
    public final CreateSharedLinkError errorValue;

    public CreateSharedLinkErrorException(String routeName, String requestId, LocalizedText userMessage, CreateSharedLinkError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
