/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.sharing;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link
 * CreateSharedLinkWithSettingsError} error.
 *
 * <p> This exception is raised by {@link
 * DbxUserSharingRequests#createSharedLinkWithSettings(String,SharedLinkSettings)}.
 * </p>
 */
public class CreateSharedLinkWithSettingsErrorException extends DbxApiException {
    // exception for routes:
    //     2/sharing/create_shared_link_with_settings

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link
     * DbxUserSharingRequests#createSharedLinkWithSettings(String,SharedLinkSettings)}.
     */
    public final CreateSharedLinkWithSettingsError errorValue;

    public CreateSharedLinkWithSettingsErrorException(String routeName, String requestId, LocalizedText userMessage, CreateSharedLinkWithSettingsError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
