/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.sharing;

import com.dropbox.core.DbxException;

/**
 * The request builder returned by {@link
 * DbxUserSharingRequests#listSharedLinksBuilder}.
 *
 * <p> Use this class to set optional request parameters and complete the
 * request. </p>
 */
public class ListSharedLinksBuilder {
    private final DbxUserSharingRequests _client;
    private final ListSharedLinksArg.Builder _builder;

    /**
     * Creates a new instance of this builder.
     *
     * @param _client  Dropbox namespace-specific client used to issue sharing
     *     requests.
     * @param _builder  Request argument builder.
     *
     * @return instsance of this builder
     */
    ListSharedLinksBuilder(DbxUserSharingRequests _client, ListSharedLinksArg.Builder _builder) {
        if (_client == null) {
            throw new NullPointerException("_client");
        }
        this._client = _client;
        if (_builder == null) {
            throw new NullPointerException("_builder");
        }
        this._builder = _builder;
    }

    /**
     * Set value for optional field.
     *
     * @param path  See {@link DbxUserSharingRequests#listSharedLinks}
     *     description. Must match pattern "{@code
     *     (/(.|[\\r\\n])*|id:.*)|(rev:[0-9a-f]{9,})|(ns:[0-9]+(/.*)?)}".
     *
     * @return this builder
     *
     * @throws IllegalArgumentException  If any argument does not meet its
     *     preconditions.
     */
    public ListSharedLinksBuilder withPath(String path) {
        this._builder.withPath(path);
        return this;
    }

    /**
     * Set value for optional field.
     *
     * @param cursor  The cursor returned by your last call to {@link
     *     DbxUserSharingRequests#listSharedLinks}.
     *
     * @return this builder
     */
    public ListSharedLinksBuilder withCursor(String cursor) {
        this._builder.withCursor(cursor);
        return this;
    }

    /**
     * Set value for optional field.
     *
     * @param directOnly  See {@link DbxUserSharingRequests#listSharedLinks}
     *     description.
     *
     * @return this builder
     */
    public ListSharedLinksBuilder withDirectOnly(Boolean directOnly) {
        this._builder.withDirectOnly(directOnly);
        return this;
    }

    /**
     * Issues the request.
     */
    public ListSharedLinksResult start() throws ListSharedLinksErrorException, DbxException {
        ListSharedLinksArg arg_ = this._builder.build();
        return _client.listSharedLinks(arg_);
    }
}
