/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.sharing;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link ListFileMembersError}
 * error.
 *
 * <p> This exception is raised by {@link
 * DbxUserSharingRequests#listFileMembers(String)}. </p>
 */
public class ListFileMembersErrorException extends DbxApiException {
    // exception for routes:
    //     2/sharing/list_file_members

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link
     * DbxUserSharingRequests#listFileMembers(String)}.
     */
    public final ListFileMembersError errorValue;

    public ListFileMembersErrorException(String routeName, String requestId, LocalizedText userMessage, ListFileMembersError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
