/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.sharing;

import com.dropbox.core.DbxException;

import java.util.List;

/**
 * The request builder returned by {@link
 * DbxUserSharingRequests#listReceivedFilesBuilder}.
 *
 * <p> Use this class to set optional request parameters and complete the
 * request. </p>
 */
public class ListReceivedFilesBuilder {
    private final DbxUserSharingRequests _client;
    private final ListFilesArg.Builder _builder;

    /**
     * Creates a new instance of this builder.
     *
     * @param _client  Dropbox namespace-specific client used to issue sharing
     *     requests.
     * @param _builder  Request argument builder.
     *
     * @return instsance of this builder
     */
    ListReceivedFilesBuilder(DbxUserSharingRequests _client, ListFilesArg.Builder _builder) {
        if (_client == null) {
            throw new NullPointerException("_client");
        }
        this._client = _client;
        if (_builder == null) {
            throw new NullPointerException("_builder");
        }
        this._builder = _builder;
    }

    /**
     * Set value for optional field.
     *
     * <p> If left unset or set to {@code null}, defaults to {@code 100L}. </p>
     *
     * @param limit  Number of files to return max per query. Defaults to 100 if
     *     no limit is specified. Must be greater than or equal to 1 and be less
     *     than or equal to 300. Defaults to {@code 100L} when set to {@code
     *     null}.
     *
     * @return this builder
     *
     * @throws IllegalArgumentException  If any argument does not meet its
     *     preconditions.
     */
    public ListReceivedFilesBuilder withLimit(Long limit) {
        this._builder.withLimit(limit);
        return this;
    }

    /**
     * Set value for optional field.
     *
     * @param actions  A list of `FileAction`s corresponding to
     *     `FilePermission`s that should appear in the  response's {@link
     *     SharedFileMetadata#getPermissions} field describing the actions the
     *     authenticated user can perform on the file. Must not contain a {@code
     *     null} item.
     *
     * @return this builder
     *
     * @throws IllegalArgumentException  If any argument does not meet its
     *     preconditions.
     */
    public ListReceivedFilesBuilder withActions(List<FileAction> actions) {
        this._builder.withActions(actions);
        return this;
    }

    /**
     * Issues the request.
     */
    public ListFilesResult start() throws SharingUserErrorException, DbxException {
        ListFilesArg arg_ = this._builder.build();
        return _client.listReceivedFiles(arg_);
    }
}
