/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.sharing;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link
 * RevokeSharedLinkError} error.
 *
 * <p> This exception is raised by {@link
 * DbxUserSharingRequests#revokeSharedLink(String)}. </p>
 */
public class RevokeSharedLinkErrorException extends DbxApiException {
    // exception for routes:
    //     2/sharing/revoke_shared_link

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link
     * DbxUserSharingRequests#revokeSharedLink(String)}.
     */
    public final RevokeSharedLinkError errorValue;

    public RevokeSharedLinkErrorException(String routeName, String requestId, LocalizedText userMessage, RevokeSharedLinkError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
