/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.sharing;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link
 * SetAccessInheritanceError} error.
 *
 * <p> This exception is raised by {@link
 * DbxUserSharingRequests#setAccessInheritance(String,AccessInheritance)}. </p>
 */
public class SetAccessInheritanceErrorException extends DbxApiException {
    // exception for routes:
    //     2/sharing/set_access_inheritance

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link
     * DbxUserSharingRequests#setAccessInheritance(String,AccessInheritance)}.
     */
    public final SetAccessInheritanceError errorValue;

    public SetAccessInheritanceErrorException(String routeName, String requestId, LocalizedText userMessage, SetAccessInheritanceError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
