/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.sharing;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link
 * SharedFolderAccessError} error.
 *
 * <p> This exception is raised by {@link
 * DbxUserSharingRequests#getFolderMetadata(String,java.util.List)} and {@link
 * DbxUserSharingRequests#listFolderMembers(String)}. </p>
 */
public class SharedFolderAccessErrorException extends DbxApiException {
    // exception for routes:
    //     2/sharing/get_folder_metadata
    //     2/sharing/list_folder_members

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link
     * DbxUserSharingRequests#getFolderMetadata(String,java.util.List)} and
     * {@link DbxUserSharingRequests#listFolderMembers(String)}.
     */
    public final SharedFolderAccessError errorValue;

    public SharedFolderAccessErrorException(String routeName, String requestId, LocalizedText userMessage, SharedFolderAccessError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
