/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.sharing;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link UnshareFolderError}
 * error.
 *
 * <p> This exception is raised by {@link
 * DbxUserSharingRequests#unshareFolder(String,boolean)}. </p>
 */
public class UnshareFolderErrorException extends DbxApiException {
    // exception for routes:
    //     2/sharing/unshare_folder

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link
     * DbxUserSharingRequests#unshareFolder(String,boolean)}.
     */
    public final UnshareFolderError errorValue;

    public UnshareFolderErrorException(String routeName, String requestId, LocalizedText userMessage, UnshareFolderError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
