/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.files;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link
 * ListFolderLongpollError} error.
 *
 * <p> This exception is raised by {@link
 * DbxUserFilesRequests#listFolderLongpoll(String,long)}. </p>
 */
public class ListFolderLongpollErrorException extends DbxApiException {
    // exception for routes:
    //     2/files/list_folder/longpoll

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link
     * DbxUserFilesRequests#listFolderLongpoll(String,long)}.
     */
    public final ListFolderLongpollError errorValue;

    public ListFolderLongpollErrorException(String routeName, String requestId, LocalizedText userMessage, ListFolderLongpollError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
