/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.files;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link
 * ListFolderContinueError} error.
 *
 * <p> This exception is raised by {@link
 * DbxUserFilesRequests#listFolderContinue(String)}. </p>
 */
public class ListFolderContinueErrorException extends DbxApiException {
    // exception for routes:
    //     2/files/list_folder/continue

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link
     * DbxUserFilesRequests#listFolderContinue(String)}.
     */
    public final ListFolderContinueError errorValue;

    public ListFolderContinueErrorException(String routeName, String requestId, LocalizedText userMessage, ListFolderContinueError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
