/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.files;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link PreviewError} error.
 *
 * <p> This exception is raised by {@link
 * DbxUserFilesRequests#getPreview(String,String)}. </p>
 */
public class PreviewErrorException extends DbxApiException {
    // exception for routes:
    //     2/files/get_preview

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link
     * DbxUserFilesRequests#getPreview(String,String)}.
     */
    public final PreviewError errorValue;

    public PreviewErrorException(String routeName, String requestId, LocalizedText userMessage, PreviewError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
