/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.files;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link UploadError} error.
 *
 * <p> This exception is raised by {@link DbxUserFilesRequests#upload(String)}.
 * </p>
 */
public class UploadErrorException extends DbxApiException {
    // exception for routes:
    //     2/files/upload

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link DbxUserFilesRequests#upload(String)}.
     */
    public final UploadError errorValue;

    public UploadErrorException(String routeName, String requestId, LocalizedText userMessage, UploadError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
