/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.files;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link
 * UploadSessionFinishError} error.
 *
 * <p> This exception is raised by {@link
 * DbxUserFilesRequests#uploadSessionFinish(UploadSessionCursor,CommitInfo)}.
 * </p>
 */
public class UploadSessionFinishErrorException extends DbxApiException {
    // exception for routes:
    //     2/files/upload_session/finish

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link
     * DbxUserFilesRequests#uploadSessionFinish(UploadSessionCursor,CommitInfo)}.
     */
    public final UploadSessionFinishError errorValue;

    public UploadSessionFinishErrorException(String routeName, String requestId, LocalizedText userMessage, UploadSessionFinishError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
