/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.files;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link
 * UploadErrorWithProperties} error.
 *
 * <p> This exception is raised by {@link
 * DbxUserFilesRequests#alphaUpload(String)}. </p>
 */
public class UploadErrorWithPropertiesException extends DbxApiException {
    // exception for routes:
    //     2/files/alpha/upload

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link DbxUserFilesRequests#alphaUpload(String)}.
     */
    public final UploadErrorWithProperties errorValue;

    public UploadErrorWithPropertiesException(String routeName, String requestId, LocalizedText userMessage, UploadErrorWithProperties errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
