/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2;

import com.dropbox.core.v2.fileproperties.DbxTeamFilePropertiesRequests;
import com.dropbox.core.v2.team.DbxTeamTeamRequests;
import com.dropbox.core.v2.teamlog.DbxTeamTeamLogRequests;

/**
 * Base class for team auth clients.
 */
public class DbxTeamClientV2Base {
    protected final DbxRawClientV2 _client;

    private final DbxTeamFilePropertiesRequests fileProperties;
    private final DbxTeamTeamRequests team;
    private final DbxTeamTeamLogRequests teamLog;

    /**
     * For internal use only.
     *
     * @param _client  Raw v2 client to use for issuing requests
     */
    protected DbxTeamClientV2Base(DbxRawClientV2 _client) {
        this._client = _client;
        this.fileProperties = new DbxTeamFilePropertiesRequests(_client);
        this.team = new DbxTeamTeamRequests(_client);
        this.teamLog = new DbxTeamTeamLogRequests(_client);
    }

    /**
     * Returns client for issuing requests in the {@code "file_properties"}
     * namespace.
     *
     * @return Dropbox file_properties client
     */
    public DbxTeamFilePropertiesRequests fileProperties() {
        return fileProperties;
    }

    /**
     * Returns client for issuing requests in the {@code "team"} namespace.
     *
     * @return Dropbox team client
     */
    public DbxTeamTeamRequests team() {
        return team;
    }

    /**
     * Returns client for issuing requests in the {@code "team_log"} namespace.
     *
     * @return Dropbox team_log client
     */
    public DbxTeamTeamLogRequests teamLog() {
        return teamLog;
    }
}
