/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.users;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link
 * UserFeaturesGetValuesBatchError} error.
 *
 * <p> This exception is raised by {@link
 * DbxUserUsersRequests#featuresGetValues(java.util.List)}. </p>
 */
public class UserFeaturesGetValuesBatchErrorException extends DbxApiException {
    // exception for routes:
    //     2/users/features/get_values

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link
     * DbxUserUsersRequests#featuresGetValues(java.util.List)}.
     */
    public final UserFeaturesGetValuesBatchError errorValue;

    public UserFeaturesGetValuesBatchErrorException(String routeName, String requestId, LocalizedText userMessage, UserFeaturesGetValuesBatchError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
