/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.stone;

import com.dropbox.core.v2.DbxRawClientV2;

/**
 * Generated Stone client.
 */
public class StoneTestClient {
    protected final DbxRawClientV2 _client;


    /**
     * For internal use only.
     *
     * @param _client  Raw v2 client to use for issuing requests
     */
    protected StoneTestClient(DbxRawClientV2 _client) {
        this._client = _client;
    }
}
