#!/usr/bin/env bash
set -euo pipefail

if [[ -z "${REFRESH_TOKEN}" ]]; then
  echo "REFRESH_TOKEN is not set. If this is running in CI, it's because secrets are not passed to forks."
  exit 2;

curl https://api.dropbox.com/oauth2/token \
    -d grant_type=refresh_token \
    -d refresh_token=$REFRESH_TOKEN \
    -d client_id=$APP_KEY > auth_output

truncate -s -1 auth_output

echo ", \
    \"app_key\": \"$APP_KEY\", \
    \"app_secret\": \"$APP_SECRET\", \
    \"refresh_token\": \"$REFRESH_TOKEN\", \
    \"expires_at\": 1 \
    }" >> auth_output
