#!/usr/bin/env bash
set -euo pipefail

REFRESH_TOKEN="a"
APP_KEY="b"
APP_SECRET="c"

curl https://api.dropbox.com/oauth2/token \
    -d grant_type=refresh_token \
    -d refresh_token=$REFRESH_TOKEN \
    -d client_id=$APP_KEY > auth_output

truncate -s -1 auth_output

echo ", \
    \"app_key\": \"$APP_KEY\", \
    \"app_secret\": \"$APP_SECRET\", \
    \"refresh_token\": \"$REFRESH_TOKEN\", \
    \"expires_at\": 1 \
    }" >> auth_output
