#!/usr/bin/env bash
set -euo pipefail

curl https://api.dropbox.com/oauth2/token \
    -d grant_type=refresh_token \
    -d refresh_token=$REFRESH_TOKEN \
    -d client_id=$APP_KEY > auth_output && truncate -s-1 auth_output

",
    "app_key": "$ENV.APP_KEY",
    "app_secret": "$APP_SECRET",
    "refresh_token": "$REFRESH_TOKEN",
    "expires_at": 1
    }" >> auth_output