#! /usr/bin/env bash
set -euo pipefail

gradle_build_dir="build"

# Locate the script file.  Cross symlinks if necessary.
loc="$0"
while [ -h "$loc" ]; do
    ls=`ls -ld "$loc"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        loc="$link"  # Absolute link
    else
        loc="`dirname "$loc"`/$link"  # Relative link
    fi
done

base_dir=`dirname "$loc"`

stone_dir="$base_dir/stone"
spec_dir="${base_dir}/spec"
gen_dir="$base_dir/$gradle_build_dir/generated-sources/stone"
generator="$base_dir/generator/java.stoneg.py"

usage() {
    echo "usage: $0 [SPEC_DIR [OUTPUT_DIR]]"
    echo ""
    echo "positional arguments:"
    echo "  SPEC_DIR     Top-level directory containing Stone spec files (default: ${spec_dir})."
    echo "  OUTPUT_DIR   Top-level directory to output generated source files (default: ${gen_dir})."
    echo ""
    echo "optional arguments:"
    echo "  -h/--help    Display this message and exit."
}

args=("${spec_dir}" "${gen_dir}")
argi=0
while [[ $# -gt 0 ]]; do
    case "$1" in
        "-h"|"--help")
            usage
            exit 1
            ;;
        *)
            args[$argi]="${1}"
            argi=$(( $argi + 1 ))
            shift
    esac
done

if [[ ${#args[@]} -gt 2 ]]; then
    echo "$0: Too many arguments" 1>&2
    usage
    exit 1
fi

spec_dir="${args[0]}"
gen_dir="${args[1]}"

if [[ -e "$gen_dir" ]]; then
    rm -r "$gen_dir"
fi

mkdir -p "$gen_dir"

echo "Generating..."
PYTHONPATH="$stone_dir" python3 -m stone.cli \
    --filter-by-route-attr 'alpha_group=null and beta_group=null' \
    "$generator" \
    "$gen_dir"\
    $(find -H "${spec_dir}" -name "*.stone") \
     -- \
     --package com.dropbox.core.v2
