/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.paper;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link PaperDocUpdateError}
 * error.
 *
 * <p> This exception is raised by {@link
 * DbxUserPaperRequests#docsUpdate(String,PaperDocUpdatePolicy,long,ImportFormat)}.
 * </p>
 */
public class PaperDocUpdateErrorException extends DbxApiException {
    // exception for routes:
    //     2/paper/docs/update

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link
     * DbxUserPaperRequests#docsUpdate(String,PaperDocUpdatePolicy,long,ImportFormat)}.
     */
    public final PaperDocUpdateError errorValue;

    public PaperDocUpdateErrorException(String routeName, String requestId, LocalizedText userMessage, PaperDocUpdateError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
