/* DO NOT EDIT */
/* This file was generated by Babel */

package com.dropbox.core.v2;

/**
 * Base class for app auth clients.
 */
public class DbxAppClientV2Base {
    protected final DbxRawClientV2 _client;


    /**
     * For internal use only.
     *
     * @param _client  Raw v2 client to use for issuing requests
     */
    protected DbxAppClientV2Base(DbxRawClientV2 _client) {
        this._client = _client;
    }
}
