/* DO NOT EDIT */
/* This file was generated by Babel */

package com.dropbox.core.v2;

import com.dropbox.core.v2.auth.DbxUserAuthRequests;
import com.dropbox.core.v2.files.DbxUserFilesRequests;
import com.dropbox.core.v2.sharing.DbxUserSharingRequests;
import com.dropbox.core.v2.users.DbxUserUsersRequests;

/**
 * Base class for user auth clients.
 */
public class DbxClientV2Base {
    protected final DbxRawClientV2 _client;

    private final DbxUserAuthRequests auth;
    private final DbxUserFilesRequests files;
    private final DbxUserSharingRequests sharing;
    private final DbxUserUsersRequests users;

    /**
     * For internal use only.
     *
     * @param _client  Raw v2 client to use for issuing requests
     */
    protected DbxClientV2Base(DbxRawClientV2 _client) {
        this._client = _client;
        this.auth = new DbxUserAuthRequests(_client);
        this.files = new DbxUserFilesRequests(_client);
        this.sharing = new DbxUserSharingRequests(_client);
        this.users = new DbxUserUsersRequests(_client);
    }

    /**
     * Returns client for issuing requests in the {@code "auth"} namespace.
     *
     * @return Dropbox auth client
     */
    public DbxUserAuthRequests auth() {
        return auth;
    }

    /**
     * Returns client for issuing requests in the {@code "files"} namespace.
     *
     * @return Dropbox files client
     */
    public DbxUserFilesRequests files() {
        return files;
    }

    /**
     * Returns client for issuing requests in the {@code "sharing"} namespace.
     *
     * @return Dropbox sharing client
     */
    public DbxUserSharingRequests sharing() {
        return sharing;
    }

    /**
     * Returns client for issuing requests in the {@code "users"} namespace.
     *
     * @return Dropbox users client
     */
    public DbxUserUsersRequests users() {
        return users;
    }
}
