/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2;

import com.dropbox.core.v2.team.DbxTeamTeamRequests;

/**
 * Base class for team auth clients.
 */
public class DbxTeamClientV2Base {
    protected final DbxRawClientV2 _client;

    private final DbxTeamTeamRequests team;

    /**
     * For internal use only.
     *
     * @param _client  Raw v2 client to use for issuing requests
     */
    protected DbxTeamClientV2Base(DbxRawClientV2 _client) {
        this._client = _client;
        this.team = new DbxTeamTeamRequests(_client);
    }

    /**
     * Returns client for issuing requests in the {@code "team"} namespace.
     *
     * @return Dropbox team client
     */
    public DbxTeamTeamRequests team() {
        return team;
    }
}
