/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.fileproperties;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link
 * PropertiesSearchError} error.
 *
 * <p> This exception is raised by {@link
 * DbxUserFilePropertiesRequests#propertiesSearch(java.util.List,TemplateFilter)}.
 * </p>
 */
public class PropertiesSearchErrorException extends DbxApiException {
    // exception for routes:
    //     2/file_properties/properties/search

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link
     * DbxUserFilePropertiesRequests#propertiesSearch(java.util.List,TemplateFilter)}.
     */
    public final PropertiesSearchError errorValue;

    public PropertiesSearchErrorException(String routeName, String requestId, LocalizedText userMessage, PropertiesSearchError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
