/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.sharing;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link
 * RemoveFolderMemberError} error.
 *
 * <p> This exception is raised by {@link
 * DbxUserSharingRequests#removeFolderMember(String,MemberSelector,boolean)}.
 * </p>
 */
public class RemoveFolderMemberErrorException extends DbxApiException {
    // exception for routes:
    //     2/sharing/remove_folder_member

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link
     * DbxUserSharingRequests#removeFolderMember(String,MemberSelector,boolean)}.
     */
    public final RemoveFolderMemberError errorValue;

    public RemoveFolderMemberErrorException(String routeName, String requestId, LocalizedText userMessage, RemoveFolderMemberError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
