/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.sharing;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link TransferFolderError}
 * error.
 *
 * <p> This exception is raised by {@link
 * DbxUserSharingRequests#transferFolder(String,String)}. </p>
 */
public class TransferFolderErrorException extends DbxApiException {
    // exception for routes:
    //     2/sharing/transfer_folder

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link
     * DbxUserSharingRequests#transferFolder(String,String)}.
     */
    public final TransferFolderError errorValue;

    public TransferFolderErrorException(String routeName, String requestId, LocalizedText userMessage, TransferFolderError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
