/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.team;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link GroupUpdateError}
 * error.
 *
 * <p> This exception is raised by {@link
 * DbxTeamTeamRequests#groupsUpdate(GroupSelector)}. </p>
 */
public class GroupUpdateErrorException extends DbxApiException {
    // exception for routes:
    //     2/team/groups/update

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link
     * DbxTeamTeamRequests#groupsUpdate(GroupSelector)}.
     */
    public final GroupUpdateError errorValue;

    public GroupUpdateErrorException(String routeName, String requestId, LocalizedText userMessage, GroupUpdateError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
