/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.team;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link
 * LegalHoldsGetPolicyError} error.
 *
 * <p> This exception is raised by {@link
 * DbxTeamTeamRequests#legalHoldsGetPolicy(String)}. </p>
 */
public class LegalHoldsGetPolicyErrorException extends DbxApiException {
    // exception for routes:
    //     2/team/legal_holds/get_policy

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link
     * DbxTeamTeamRequests#legalHoldsGetPolicy(String)}.
     */
    public final LegalHoldsGetPolicyError errorValue;

    public LegalHoldsGetPolicyErrorException(String routeName, String requestId, LocalizedText userMessage, LegalHoldsGetPolicyError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
