/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.team;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link ListTeamAppsError}
 * error.
 *
 * <p> This exception is raised by {@link
 * DbxTeamTeamRequests#linkedAppsListTeamLinkedApps(String)}. </p>
 */
public class ListTeamAppsErrorException extends DbxApiException {
    // exception for routes:
    //     2/team/linked_apps/list_team_linked_apps

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link
     * DbxTeamTeamRequests#linkedAppsListTeamLinkedApps(String)}.
     */
    public final ListTeamAppsError errorValue;

    public ListTeamAppsErrorException(String routeName, String requestId, LocalizedText userMessage, ListTeamAppsError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
