/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.team;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link ListTeamDevicesError}
 * error.
 *
 * <p> This exception is raised by {@link
 * DbxTeamTeamRequests#devicesListTeamDevices}. </p>
 */
public class ListTeamDevicesErrorException extends DbxApiException {
    // exception for routes:
    //     2/team/devices/list_team_devices

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link DbxTeamTeamRequests#devicesListTeamDevices}.
     */
    public final ListTeamDevicesError errorValue;

    public ListTeamDevicesErrorException(String routeName, String requestId, LocalizedText userMessage, ListTeamDevicesError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
