/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.team;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link
 * RevokeDeviceSessionBatchError} error.
 *
 * <p> This exception is raised by {@link
 * DbxTeamTeamRequests#devicesRevokeDeviceSessionBatch(java.util.List)}. </p>
 */
public class RevokeDeviceSessionBatchErrorException extends DbxApiException {
    // exception for routes:
    //     2/team/devices/revoke_device_session_batch

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link
     * DbxTeamTeamRequests#devicesRevokeDeviceSessionBatch(java.util.List)}.
     */
    public final RevokeDeviceSessionBatchError errorValue;

    public RevokeDeviceSessionBatchErrorException(String routeName, String requestId, LocalizedText userMessage, RevokeDeviceSessionBatchError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
