/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.team;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link
 * GroupsListContinueError} error.
 *
 * <p> This exception is raised by {@link
 * DbxTeamTeamRequests#groupsListContinue(String)}. </p>
 */
public class GroupsListContinueErrorException extends DbxApiException {
    // exception for routes:
    //     2/team/groups/list/continue

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link
     * DbxTeamTeamRequests#groupsListContinue(String)}.
     */
    public final GroupsListContinueError errorValue;

    public GroupsListContinueErrorException(String routeName, String requestId, LocalizedText userMessage, GroupsListContinueError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
