/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.team;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link
 * LegalHoldsExportPolicyError} error.
 *
 * <p> This exception is raised by {@link
 * DbxTeamTeamRequests#legalHoldsExportPolicy(String,String)}. </p>
 */
public class LegalHoldsExportPolicyErrorException extends DbxApiException {
    // exception for routes:
    //     2/team/legal_holds/export_policy

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link
     * DbxTeamTeamRequests#legalHoldsExportPolicy(String,String)}.
     */
    public final LegalHoldsExportPolicyError errorValue;

    public LegalHoldsExportPolicyErrorException(String routeName, String requestId, LocalizedText userMessage, LegalHoldsExportPolicyError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
