/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.team;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link ListMembersAppsError}
 * error.
 *
 * <p> This exception is raised by {@link
 * DbxTeamTeamRequests#linkedAppsListMembersLinkedApps(String)}. </p>
 */
public class ListMembersAppsErrorException extends DbxApiException {
    // exception for routes:
    //     2/team/linked_apps/list_members_linked_apps

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link
     * DbxTeamTeamRequests#linkedAppsListMembersLinkedApps(String)}.
     */
    public final ListMembersAppsError errorValue;

    public ListMembersAppsErrorException(String routeName, String requestId, LocalizedText userMessage, ListMembersAppsError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
