/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.team;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link
 * MembersDeleteProfilePhotoError} error.
 *
 * <p> This exception is raised by {@link
 * DbxTeamTeamRequests#membersDeleteProfilePhoto(UserSelectorArg)}. </p>
 */
public class MembersDeleteProfilePhotoErrorException extends DbxApiException {
    // exception for routes:
    //     2/team/members/delete_profile_photo

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link
     * DbxTeamTeamRequests#membersDeleteProfilePhoto(UserSelectorArg)}.
     */
    public final MembersDeleteProfilePhotoError errorValue;

    public MembersDeleteProfilePhotoErrorException(String routeName, String requestId, LocalizedText userMessage, MembersDeleteProfilePhotoError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
