/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.team;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link
 * MembersListContinueError} error.
 *
 * <p> This exception is raised by {@link
 * DbxTeamTeamRequests#membersListContinue(String)}. </p>
 */
public class MembersListContinueErrorException extends DbxApiException {
    // exception for routes:
    //     2/team/members/list/continue

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link
     * DbxTeamTeamRequests#membersListContinue(String)}.
     */
    public final MembersListContinueError errorValue;

    public MembersListContinueErrorException(String routeName, String requestId, LocalizedText userMessage, MembersListContinueError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
