/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.team;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link
 * MembersSetPermissionsError} error.
 *
 * <p> This exception is raised by {@link
 * DbxTeamTeamRequests#membersSetAdminPermissions(UserSelectorArg,AdminTier)}.
 * </p>
 */
public class MembersSetPermissionsErrorException extends DbxApiException {
    // exception for routes:
    //     2/team/members/set_admin_permissions

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link
     * DbxTeamTeamRequests#membersSetAdminPermissions(UserSelectorArg,AdminTier)}.
     */
    public final MembersSetPermissionsError errorValue;

    public MembersSetPermissionsErrorException(String routeName, String requestId, LocalizedText userMessage, MembersSetPermissionsError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
