/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.team;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link
 * MembersSetProfileError} error.
 *
 * <p> This exception is raised by {@link
 * DbxTeamTeamRequests#membersSetProfile(UserSelectorArg)}. </p>
 */
public class MembersSetProfileErrorException extends DbxApiException {
    // exception for routes:
    //     2/team/members/set_profile

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link
     * DbxTeamTeamRequests#membersSetProfile(UserSelectorArg)}.
     */
    public final MembersSetProfileError errorValue;

    public MembersSetProfileErrorException(String routeName, String requestId, LocalizedText userMessage, MembersSetProfileError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
