/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.team;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link
 * TeamFolderActivateError} error.
 *
 * <p> This exception is raised by {@link
 * DbxTeamTeamRequests#teamFolderActivate(String)}. </p>
 */
public class TeamFolderActivateErrorException extends DbxApiException {
    // exception for routes:
    //     2/team/team_folder/activate

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link
     * DbxTeamTeamRequests#teamFolderActivate(String)}.
     */
    public final TeamFolderActivateError errorValue;

    public TeamFolderActivateErrorException(String routeName, String requestId, LocalizedText userMessage, TeamFolderActivateError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
