/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.fileproperties;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link
 * UpdatePropertiesError} error.
 *
 * <p> This exception is raised by {@link
 * DbxUserFilePropertiesRequests#propertiesUpdate(String,java.util.List)} and
 * {@link
 * com.dropbox.core.v2.files.DbxUserFilesRequests#propertiesUpdate(String,java.util.List)}.
 * </p>
 */
public class UpdatePropertiesErrorException extends DbxApiException {
    // exception for routes:
    //     2/file_properties/properties/update
    //     2/files/properties/update

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link
     * DbxUserFilePropertiesRequests#propertiesUpdate(String,java.util.List)}
     * and {@link
     * com.dropbox.core.v2.files.DbxUserFilesRequests#propertiesUpdate(String,java.util.List)}.
     */
    public final UpdatePropertiesError errorValue;

    public UpdatePropertiesErrorException(String routeName, String requestId, LocalizedText userMessage, UpdatePropertiesError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
