/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2;

import com.dropbox.core.v2.auth.DbxAppAuthRequests;
import com.dropbox.core.v2.check.DbxAppCheckRequests;
import com.dropbox.core.v2.files.DbxAppFilesRequests;
import com.dropbox.core.v2.sharing.DbxAppSharingRequests;

/**
 * Base class for app auth clients.
 */
public class DbxAppClientV2Base {
    protected final DbxRawClientV2 _client;

    private final DbxAppAuthRequests auth;
    private final DbxAppCheckRequests check;
    private final DbxAppFilesRequests files;
    private final DbxAppSharingRequests sharing;

    /**
     * For internal use only.
     *
     * @param _client  Raw v2 client to use for issuing requests
     */
    protected DbxAppClientV2Base(DbxRawClientV2 _client) {
        this._client = _client;
        this.auth = new DbxAppAuthRequests(_client);
        this.check = new DbxAppCheckRequests(_client);
        this.files = new DbxAppFilesRequests(_client);
        this.sharing = new DbxAppSharingRequests(_client);
    }

    /**
     * Returns client for issuing requests in the {@code "auth"} namespace.
     *
     * @return Dropbox auth client
     */
    public DbxAppAuthRequests auth() {
        return auth;
    }

    /**
     * Returns client for issuing requests in the {@code "check"} namespace.
     *
     * @return Dropbox check client
     */
    public DbxAppCheckRequests check() {
        return check;
    }

    /**
     * Returns client for issuing requests in the {@code "files"} namespace.
     *
     * @return Dropbox files client
     */
    public DbxAppFilesRequests files() {
        return files;
    }

    /**
     * Returns client for issuing requests in the {@code "sharing"} namespace.
     *
     * @return Dropbox sharing client
     */
    public DbxAppSharingRequests sharing() {
        return sharing;
    }
}
