/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.filerequests;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link
 * CountFileRequestsError} error.
 *
 * <p> This exception is raised by {@link DbxUserFileRequestsRequests#count}.
 * </p>
 */
public class CountFileRequestsErrorException extends DbxApiException {
    // exception for routes:
    //     2/file_requests/count

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link DbxUserFileRequestsRequests#count}.
     */
    public final CountFileRequestsError errorValue;

    public CountFileRequestsErrorException(String routeName, String requestId, LocalizedText userMessage, CountFileRequestsError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
