/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.team;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link DateRangeError}
 * error.
 *
 * <p> This exception is raised by {@link
 * DbxTeamTeamRequests#reportsGetActivity}, {@link
 * DbxTeamTeamRequests#reportsGetDevices}, {@link
 * DbxTeamTeamRequests#reportsGetMembership}, and {@link
 * DbxTeamTeamRequests#reportsGetStorage}. </p>
 */
public class DateRangeErrorException extends DbxApiException {
    // exception for routes:
    //     2/team/reports/get_activity
    //     2/team/reports/get_devices
    //     2/team/reports/get_membership
    //     2/team/reports/get_storage

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link DbxTeamTeamRequests#reportsGetActivity},
     * {@link DbxTeamTeamRequests#reportsGetDevices}, {@link
     * DbxTeamTeamRequests#reportsGetMembership}, and {@link
     * DbxTeamTeamRequests#reportsGetStorage}.
     */
    public final DateRangeError errorValue;

    public DateRangeErrorException(String routeName, String requestId, LocalizedText userMessage, DateRangeError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
