/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.team;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link MembersRemoveError}
 * error.
 *
 * <p> This exception is raised by {@link
 * DbxTeamTeamRequests#membersRemove(UserSelectorArg)}. </p>
 */
public class MembersRemoveErrorException extends DbxApiException {
    // exception for routes:
    //     2/team/members/remove

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link
     * DbxTeamTeamRequests#membersRemove(UserSelectorArg)}.
     */
    public final MembersRemoveError errorValue;

    public MembersRemoveErrorException(String routeName, String requestId, LocalizedText userMessage, MembersRemoveError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
