/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.team;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link
 * ExcludedUsersListContinueError} error.
 *
 * <p> This exception is raised by {@link
 * DbxTeamTeamRequests#memberSpaceLimitsExcludedUsersListContinue(String)}. </p>
 */
public class ExcludedUsersListContinueErrorException extends DbxApiException {
    // exception for routes:
    //     2/team/member_space_limits/excluded_users/list/continue

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link
     * DbxTeamTeamRequests#memberSpaceLimitsExcludedUsersListContinue(String)}.
     */
    public final ExcludedUsersListContinueError errorValue;

    public ExcludedUsersListContinueErrorException(String routeName, String requestId, LocalizedText userMessage, ExcludedUsersListContinueError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
