/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.team;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link
 * GroupsMembersListContinueError} error.
 *
 * <p> This exception is raised by {@link
 * DbxTeamTeamRequests#groupsMembersListContinue(String)}. </p>
 */
public class GroupsMembersListContinueErrorException extends DbxApiException {
    // exception for routes:
    //     2/team/groups/members/list/continue

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link
     * DbxTeamTeamRequests#groupsMembersListContinue(String)}.
     */
    public final GroupsMembersListContinueError errorValue;

    public GroupsMembersListContinueErrorException(String routeName, String requestId, LocalizedText userMessage, GroupsMembersListContinueError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
