/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.team;

import com.dropbox.core.DbxException;

/**
 * The request builder returned by {@link
 * DbxTeamTeamRequests#membersListBuilder}.
 *
 * <p> Use this class to set optional request parameters and complete the
 * request. </p>
 */
public class MembersListBuilder {
    private final DbxTeamTeamRequests _client;
    private final MembersListArg.Builder _builder;

    /**
     * Creates a new instance of this builder.
     *
     * @param _client  Dropbox namespace-specific client used to issue team
     *     requests.
     * @param _builder  Request argument builder.
     *
     * @return instsance of this builder
     */
    MembersListBuilder(DbxTeamTeamRequests _client, MembersListArg.Builder _builder) {
        if (_client == null) {
            throw new NullPointerException("_client");
        }
        this._client = _client;
        if (_builder == null) {
            throw new NullPointerException("_builder");
        }
        this._builder = _builder;
    }

    /**
     * Set value for optional field.
     *
     * <p> If left unset or set to {@code null}, defaults to {@code 1000L}. </p>
     *
     * @param limit  Number of results to return per call. Must be greater than
     *     or equal to 1 and be less than or equal to 1000. Defaults to {@code
     *     1000L} when set to {@code null}.
     *
     * @return this builder
     *
     * @throws IllegalArgumentException  If any argument does not meet its
     *     preconditions.
     */
    public MembersListBuilder withLimit(Long limit) {
        this._builder.withLimit(limit);
        return this;
    }

    /**
     * Set value for optional field.
     *
     * <p> If left unset or set to {@code null}, defaults to {@code false}. </p>
     *
     * @param includeRemoved  Whether to return removed members. Defaults to
     *     {@code false} when set to {@code null}.
     *
     * @return this builder
     */
    public MembersListBuilder withIncludeRemoved(Boolean includeRemoved) {
        this._builder.withIncludeRemoved(includeRemoved);
        return this;
    }

    /**
     * Issues the request.
     */
    public MembersListResult start() throws MembersListErrorException, DbxException {
        MembersListArg arg_ = this._builder.build();
        return _client.membersList(arg_);
    }
}
