/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.team;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link
 * TokenGetAuthenticatedAdminError} error.
 *
 * <p> This exception is raised by {@link
 * DbxTeamTeamRequests#tokenGetAuthenticatedAdmin}. </p>
 */
public class TokenGetAuthenticatedAdminErrorException extends DbxApiException {
    // exception for routes:
    //     2/team/token/get_authenticated_admin

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link
     * DbxTeamTeamRequests#tokenGetAuthenticatedAdmin}.
     */
    public final TokenGetAuthenticatedAdminError errorValue;

    public TokenGetAuthenticatedAdminErrorException(String routeName, String requestId, LocalizedText userMessage, TokenGetAuthenticatedAdminError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
