/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.account;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link SetProfilePhotoError}
 * error.
 *
 * <p> This exception is raised by {@link
 * DbxUserAccountRequests#setProfilePhoto(PhotoSourceArg)}. </p>
 */
public class SetProfilePhotoErrorException extends DbxApiException {
    // exception for routes:
    //     2/account/set_profile_photo

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link
     * DbxUserAccountRequests#setProfilePhoto(PhotoSourceArg)}.
     */
    public final SetProfilePhotoError errorValue;

    public SetProfilePhotoErrorException(String routeName, String requestId, LocalizedText userMessage, SetProfilePhotoError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
