/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.files;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link
 * AlphaGetMetadataError} error.
 *
 * <p> This exception is raised by {@link
 * DbxUserFilesRequests#alphaGetMetadata(String)}. </p>
 */
public class AlphaGetMetadataErrorException extends DbxApiException {
    // exception for routes:
    //     2/files/alpha/get_metadata

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link
     * DbxUserFilesRequests#alphaGetMetadata(String)}.
     */
    public final AlphaGetMetadataError errorValue;

    public AlphaGetMetadataErrorException(String routeName, String requestId, LocalizedText userMessage, AlphaGetMetadataError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
