/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.files;

import com.dropbox.core.DbxException;

/**
 * The request builder returned by {@link DbxUserFilesRequests#searchV2Builder}.
 *
 * <p> Use this class to set optional request parameters and complete the
 * request. </p>
 */
public class SearchV2Builder {
    private final DbxUserFilesRequests _client;
    private final SearchV2Arg.Builder _builder;

    /**
     * Creates a new instance of this builder.
     *
     * @param _client  Dropbox namespace-specific client used to issue files
     *     requests.
     * @param _builder  Request argument builder.
     *
     * @return instsance of this builder
     */
    SearchV2Builder(DbxUserFilesRequests _client, SearchV2Arg.Builder _builder) {
        if (_client == null) {
            throw new NullPointerException("_client");
        }
        this._client = _client;
        if (_builder == null) {
            throw new NullPointerException("_builder");
        }
        this._builder = _builder;
    }

    /**
     * Set value for optional field.
     *
     * @param options  Options for more targeted search results.
     *
     * @return this builder
     */
    public SearchV2Builder withOptions(SearchOptions options) {
        this._builder.withOptions(options);
        return this;
    }

    /**
     * Set value for optional field.
     *
     * @param matchFieldOptions  Options for search results match fields.
     *
     * @return this builder
     */
    public SearchV2Builder withMatchFieldOptions(SearchMatchFieldOptions matchFieldOptions) {
        this._builder.withMatchFieldOptions(matchFieldOptions);
        return this;
    }

    /**
     * Set value for optional field.
     *
     * @param includeHighlights  Deprecated and moved this option to
     *     SearchMatchFieldOptions.
     *
     * @return this builder
     */
    public SearchV2Builder withIncludeHighlights(Boolean includeHighlights) {
        this._builder.withIncludeHighlights(includeHighlights);
        return this;
    }

    /**
     * Issues the request.
     */
    public SearchV2Result start() throws SearchErrorException, DbxException {
        SearchV2Arg arg_ = this._builder.build();
        return _client.searchV2(arg_);
    }
}
