name: Dispatch Spec Update
on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Dispatch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repository: ['dropbox/dropbox-sdk-python', 'dropbox/dropbox-sdk-js', 'dropbox/dropbox-sdk-dotnet', 'dropbox/dropbox-api-v2-explorer']
    steps:
      - name: Dispatch Update
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.SPEC_UPDATE_TOKEN }}
          repository: ${{ matrix.repository }}
          event-type: spec_update
      