/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.paper;

import com.dropbox.core.DbxException;

import java.util.List;

/**
 * The request builder returned by {@link
 * DbxUserPaperRequests#docsUsersAddBuilder}.
 *
 * <p> Use this class to set optional request parameters and complete the
 * request. </p>
 */
public class DocsUsersAddBuilder {
    private final DbxUserPaperRequests _client;
    private final AddPaperDocUser.Builder _builder;

    /**
     * Creates a new instance of this builder.
     *
     * @param _client  Dropbox namespace-specific client used to issue paper
     *     requests.
     * @param _builder  Request argument builder.
     *
     * @return instsance of this builder
     */
    DocsUsersAddBuilder(DbxUserPaperRequests _client, AddPaperDocUser.Builder _builder) {
        if (_client == null) {
            throw new NullPointerException("_client");
        }
        this._client = _client;
        if (_builder == null) {
            throw new NullPointerException("_builder");
        }
        this._builder = _builder;
    }

    /**
     * Set value for optional field.
     *
     * @param customMessage  A personal message that will be emailed to each
     *     successfully added member.
     *
     * @return this builder
     */
    public DocsUsersAddBuilder withCustomMessage(String customMessage) {
        this._builder.withCustomMessage(customMessage);
        return this;
    }

    /**
     * Set value for optional field.
     *
     * <p> If left unset or set to {@code null}, defaults to {@code false}. </p>
     *
     * @param quiet  Clients should set this to true if no email message shall
     *     be sent to added users. Defaults to {@code false} when set to {@code
     *     null}.
     *
     * @return this builder
     */
    public DocsUsersAddBuilder withQuiet(Boolean quiet) {
        this._builder.withQuiet(quiet);
        return this;
    }

    /**
     * Issues the request.
     */
    @SuppressWarnings("deprecation")
    public List<AddPaperDocUserMemberResult> start() throws DocLookupErrorException, DbxException {
        AddPaperDocUser arg_ = this._builder.build();
        return _client.docsUsersAdd(arg_);
    }
}
