/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.paper;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link ListUsersCursorError}
 * error.
 *
 * <p> This exception is raised by {@link
 * DbxUserPaperRequests#docsFolderUsersListContinue(String,String)} and {@link
 * DbxUserPaperRequests#docsUsersListContinue(String,String)}. </p>
 */
public class ListUsersCursorErrorException extends DbxApiException {
    // exception for routes:
    //     2/paper/docs/folder_users/list/continue
    //     2/paper/docs/users/list/continue

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link
     * DbxUserPaperRequests#docsFolderUsersListContinue(String,String)} and
     * {@link DbxUserPaperRequests#docsUsersListContinue(String,String)}.
     */
    public final ListUsersCursorError errorValue;

    public ListUsersCursorErrorException(String routeName, String requestId, LocalizedText userMessage, ListUsersCursorError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
