/* DO NOT EDIT */
/* This file was generated by Stone */

/**
 * See {@link com.dropbox.core.v2.auth.DbxAppAuthRequests}, {@link
 * com.dropbox.core.v2.auth.DbxUserAuthRequests} for a list of possible requests
 * for this namespace.
 */
package com.dropbox.core.v2.auth;

