/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.users;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link GetAccountError}
 * error.
 *
 * <p> This exception is raised by {@link
 * DbxUserUsersRequests#getAccount(String)}. </p>
 */
public class GetAccountErrorException extends DbxApiException {
    // exception for routes:
    //     2/users/get_account

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link DbxUserUsersRequests#getAccount(String)}.
     */
    public final GetAccountError errorValue;

    public GetAccountErrorException(String routeName, String requestId, LocalizedText userMessage, GetAccountError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
