/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.paper;

import com.dropbox.core.DbxUploader;
import com.dropbox.core.DbxWrappedException;
import com.dropbox.core.http.HttpRequestor;

import java.io.IOException;

/**
 * The {@link DbxUploader} returned by {@link
 * DbxUserPaperRequests#docsUpdate(String,PaperDocUpdatePolicy,long,ImportFormat)}.
 *
 * <p> Use this class to upload data to the server and complete the request.
 * </p>
 *
 * <p> This class should be properly closed after use to prevent resource leaks
 * and allow network connection reuse. Always call {@link #close} when complete
 * (see {@link DbxUploader} for examples). </p>
 */
public class DocsUpdateUploader extends DbxUploader<PaperDocCreateUpdateResult, PaperDocUpdateError, PaperDocUpdateErrorException> {

    /**
     * Creates a new instance of this uploader.
     *
     * @param httpUploader  Initiated HTTP upload request
     *
     * @throws NullPointerException  if {@code httpUploader} is {@code null}
     */
    public DocsUpdateUploader(HttpRequestor.Uploader httpUploader, String userId) {
        super(httpUploader, PaperDocCreateUpdateResult.Serializer.INSTANCE, PaperDocUpdateError.Serializer.INSTANCE, userId);
    }

    protected PaperDocUpdateErrorException newException(DbxWrappedException error) {
        return new PaperDocUpdateErrorException("2/paper/docs/update", error.getRequestId(), error.getUserMessage(), (PaperDocUpdateError) error.getErrorValue());
    }
}
