/* DO NOT EDIT */
/* This file was generated by Stone */

/**
 * See {@link com.dropbox.core.v2.openid.DbxUserOpenidRequests} for a list of
 * possible requests for this namespace.
 */
package com.dropbox.core.v2.openid;

