/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.stone;

import com.dropbox.core.stone.test.DbxTestTestRequests;
import com.dropbox.core.v2.DbxRawClientV2;

/**
 * TestClass.
 */
public class DbxClientV2Base {
    protected final DbxRawClientV2 _client;

    private final DbxTestTestRequests test;

    /**
     * For internal use only.
     *
     * @param _client  Raw v2 client to use for issuing requests
     */
    protected DbxClientV2Base(DbxRawClientV2 _client) {
        this._client = _client;
        this.test = new DbxTestTestRequests(_client);
    }

    /**
     * Returns client for issuing requests in the {@code "test"} namespace.
     *
     * @return Dropbox test client
     */
    public DbxTestTestRequests test() {
        return test;
    }
}
