/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.contacts;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link
 * DeleteManualContactsError} error.
 *
 * <p> This exception is raised by {@link
 * DbxUserContactsRequests#deleteManualContactsBatch(java.util.List)}. </p>
 */
public class DeleteManualContactsErrorException extends DbxApiException {
    // exception for routes:
    //     2/contacts/delete_manual_contacts_batch

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link
     * DbxUserContactsRequests#deleteManualContactsBatch(java.util.List)}.
     */
    public final DeleteManualContactsError errorValue;

    public DeleteManualContactsErrorException(String routeName, String requestId, LocalizedText userMessage, DeleteManualContactsError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
