/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.fileproperties;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link
 * PropertiesSearchContinueError} error.
 *
 * <p> This exception is raised by {@link
 * DbxUserFilePropertiesRequests#propertiesSearchContinue(String)}. </p>
 */
public class PropertiesSearchContinueErrorException extends DbxApiException {
    // exception for routes:
    //     2/file_properties/properties/search/continue

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link
     * DbxUserFilePropertiesRequests#propertiesSearchContinue(String)}.
     */
    public final PropertiesSearchContinueError errorValue;

    public PropertiesSearchContinueErrorException(String routeName, String requestId, LocalizedText userMessage, PropertiesSearchContinueError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
