/* DO NOT EDIT */
/* This file was generated by Stone */

/**
 * See {@link com.dropbox.core.stone.test.DbxTestTestRequests} for a list of
 * possible requests for this namespace.
 */
package com.dropbox.core.stone.test;

