/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.sharing;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link MountFolderError}
 * error.
 *
 * <p> This exception is raised by {@link
 * DbxUserSharingRequests#mountFolder(String)}. </p>
 */
public class MountFolderErrorException extends DbxApiException {
    // exception for routes:
    //     2/sharing/mount_folder

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link DbxUserSharingRequests#mountFolder(String)}.
     */
    public final MountFolderError errorValue;

    public MountFolderErrorException(String routeName, String requestId, LocalizedText userMessage, MountFolderError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
