/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.users;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link GetAccountBatchError}
 * error.
 *
 * <p> This exception is raised by {@link
 * DbxUserUsersRequests#getAccountBatch(java.util.List)}. </p>
 */
public class GetAccountBatchErrorException extends DbxApiException {
    // exception for routes:
    //     2/users/get_account_batch

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link
     * DbxUserUsersRequests#getAccountBatch(java.util.List)}.
     */
    public final GetAccountBatchError errorValue;

    public GetAccountBatchErrorException(String routeName, String requestId, LocalizedText userMessage, GetAccountBatchError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
