/* DO NOT EDIT */
/* This file was generated by Stone */

/**
 * This namespace contains endpoints and data types for user management.
 *
 * <p> See {@link com.dropbox.core.v2.users.DbxUserUsersRequests} for a list of
 * possible requests for this namespace. </p>
 */
package com.dropbox.core.v2.users;

