/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.filerequests;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link
 * CreateFileRequestError} error.
 *
 * <p> This exception is raised by {@link
 * DbxUserFileRequestsRequests#create(String,String)}. </p>
 */
public class CreateFileRequestErrorException extends DbxApiException {
    // exception for routes:
    //     2/file_requests/create

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link
     * DbxUserFileRequestsRequests#create(String,String)}.
     */
    public final CreateFileRequestError errorValue;

    public CreateFileRequestErrorException(String routeName, String requestId, LocalizedText userMessage, CreateFileRequestError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
