/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.paper;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link PaperDocCreateError}
 * error.
 *
 * <p> This exception is raised by {@link
 * DbxUserPaperRequests#docsCreate(ImportFormat,String)}. </p>
 */
public class PaperDocCreateErrorException extends DbxApiException {
    // exception for routes:
    //     2/paper/docs/create

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link
     * DbxUserPaperRequests#docsCreate(ImportFormat,String)}.
     */
    public final PaperDocCreateError errorValue;

    public PaperDocCreateErrorException(String routeName, String requestId, LocalizedText userMessage, PaperDocCreateError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
