#!/usr/bin/env bash
if [[ $(git status --porcelain) != '' ]]; then
    echo "Working directory is dirty. Please check that you committed any changes after running ./gradlew :generateStone";
    exit 1
else
    echo "Working directory is clean!"
    exit 0
fi