/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2;

import com.dropbox.core.v2.auth.DbxAppAuthRequests;
import com.dropbox.core.v2.check.DbxAppCheckRequests;

/**
 * Base class for app auth clients.
 */
public class DbxAppClientV2Base {
    protected final DbxRawClientV2 _client;

    private final DbxAppAuthRequests auth;
    private final DbxAppCheckRequests check;

    /**
     * For internal use only.
     *
     * @param _client  Raw v2 client to use for issuing requests
     */
    protected DbxAppClientV2Base(DbxRawClientV2 _client) {
        this._client = _client;
        this.auth = new DbxAppAuthRequests(_client);
        this.check = new DbxAppCheckRequests(_client);
    }

    /**
     * Returns client for issuing requests in the {@code "auth"} namespace.
     *
     * @return Dropbox auth client
     */
    public DbxAppAuthRequests auth() {
        return auth;
    }

    /**
     * Returns client for issuing requests in the {@code "check"} namespace.
     *
     * @return Dropbox check client
     */
    public DbxAppCheckRequests check() {
        return check;
    }
}
