/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.filerequests;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link
 * DeleteFileRequestError} error.
 *
 * <p> This exception is raised by {@link
 * DbxUserFileRequestsRequests#delete(java.util.List)}. </p>
 */
public class DeleteFileRequestErrorException extends DbxApiException {
    // exception for routes:
    //     2/file_requests/delete

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link
     * DbxUserFileRequestsRequests#delete(java.util.List)}.
     */
    public final DeleteFileRequestError errorValue;

    public DeleteFileRequestErrorException(String routeName, String requestId, LocalizedText userMessage, DeleteFileRequestError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
