/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.filerequests;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link GetFileRequestError}
 * error.
 *
 * <p> This exception is raised by {@link
 * DbxUserFileRequestsRequests#get(String)}. </p>
 */
public class GetFileRequestErrorException extends DbxApiException {
    // exception for routes:
    //     2/file_requests/get

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link DbxUserFileRequestsRequests#get(String)}.
     */
    public final GetFileRequestError errorValue;

    public GetFileRequestErrorException(String routeName, String requestId, LocalizedText userMessage, GetFileRequestError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
