/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.stone.test;

import com.dropbox.core.DbxDownloader;
import com.dropbox.core.DbxException;
import com.dropbox.core.v2.DbxDownloadStyleBuilder;

/**
 * The request builder returned by {@link
 * DbxTestTestRequests#testDownloadV2Builder}.
 *
 * <p> Use this class to set optional request parameters and complete the
 * request. </p>
 */
public class TestDownloadV2Builder extends DbxDownloadStyleBuilder<Fish> {
    private final DbxTestTestRequests _client;
    private final UninitializedReason reason;
    private final String sessionId;

    /**
     * Creates a new instance of this builder.
     *
     * @param reason  Must not be {@code null}.
     * @param sessionId  Must not be {@code null}.
     * @param _client  Dropbox namespace-specific client used to issue test
     *     requests.
     *
     * @return instsance of this builder
     *
     * @throws IllegalArgumentException  If any argument does not meet its
     *     preconditions.
     */
    TestDownloadV2Builder(DbxTestTestRequests _client, UninitializedReason reason, String sessionId) {
        if (_client == null) {
            throw new NullPointerException("_client");
        }
        this._client = _client;
        this.reason = reason;
        this.sessionId = sessionId;
    }

    @Override
    public DbxDownloader<Fish> start() throws ParentUnionException, DbxException {
        Uninitialized arg_ = new Uninitialized(reason, sessionId);
        return _client.testDownloadV2(arg_, getHeaders());
    }
}
