/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.stone.test;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.DbxDownloader;
import com.dropbox.core.DbxException;
import com.dropbox.core.util.LangUtil;
import com.dropbox.core.v2.DbxDownloadStyleBuilder;

import java.util.Date;

/**
 * The request builder returned by {@link
 * DbxTestTestRequests#testDownloadBuilder}.
 *
 * <p> Use this class to set optional request parameters and complete the
 * request. </p>
 */
public class TestDownloadBuilder extends DbxDownloadStyleBuilder<Fish> {
    private final DbxTestTestRequests _client;
    private final Dog.Builder _builder;

    /**
     * Creates a new instance of this builder.
     *
     * @param _client  Dropbox namespace-specific client used to issue test
     *     requests.
     * @param _builder  Request argument builder.
     *
     * @return instsance of this builder
     */
    TestDownloadBuilder(DbxTestTestRequests _client, Dog.Builder _builder) {
        if (_client == null) {
            throw new NullPointerException("_client");
        }
        this._client = _client;
        if (_builder == null) {
            throw new NullPointerException("_builder");
        }
        this._builder = _builder;
    }

    /**
     * Set value for optional field.
     *
     * @return this builder
     */
    public TestDownloadBuilder withBorn(Date born) {
        this._builder.withBorn(born);
        return this;
    }

    /**
     * Set value for optional field.
     *
     * @return this builder
     */
    public TestDownloadBuilder withSize(DogSize size) {
        this._builder.withSize(size);
        return this;
    }

    @Override
    public DbxDownloader<Fish> start() throws DbxApiException, DbxException {
        Dog arg_ = this._builder.build();
        return _client.testDownload(arg_, getHeaders());
    }
}
