/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.files;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link
 * GetTemporaryLinkError} error.
 *
 * <p> This exception is raised by {@link
 * DbxUserFilesRequests#getTemporaryLink(String)}. </p>
 */
public class GetTemporaryLinkErrorException extends DbxApiException {
    // exception for routes:
    //     2/files/get_temporary_link

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link
     * DbxUserFilesRequests#getTemporaryLink(String)}.
     */
    public final GetTemporaryLinkError errorValue;

    public GetTemporaryLinkErrorException(String routeName, String requestId, LocalizedText userMessage, GetTemporaryLinkError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
