/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.files;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link LockFileError} error.
 *
 * <p> This exception is raised by {@link
 * DbxUserFilesRequests#getFileLockBatch(java.util.List)}, {@link
 * DbxUserFilesRequests#lockFileBatch(java.util.List)}, and {@link
 * DbxUserFilesRequests#unlockFileBatch(java.util.List)}. </p>
 */
public class LockFileErrorException extends DbxApiException {
    // exception for routes:
    //     2/files/get_file_lock_batch
    //     2/files/lock_file_batch
    //     2/files/unlock_file_batch

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link
     * DbxUserFilesRequests#getFileLockBatch(java.util.List)}, {@link
     * DbxUserFilesRequests#lockFileBatch(java.util.List)}, and {@link
     * DbxUserFilesRequests#unlockFileBatch(java.util.List)}.
     */
    public final LockFileError errorValue;

    public LockFileErrorException(String routeName, String requestId, LocalizedText userMessage, LockFileError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
