/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.files;

import com.dropbox.core.DbxUploader;
import com.dropbox.core.DbxWrappedException;
import com.dropbox.core.http.HttpRequestor;

import java.io.IOException;

/**
 * The {@link DbxUploader} returned by {@link
 * DbxUserFilesRequests#paperUpdate(String,ImportFormat,PaperDocUpdatePolicy,Long)}.
 *
 * <p> Use this class to upload data to the server and complete the request.
 * </p>
 *
 * <p> This class should be properly closed after use to prevent resource leaks
 * and allow network connection reuse. Always call {@link #close} when complete
 * (see {@link DbxUploader} for examples). </p>
 */
public class PaperUpdateUploader extends DbxUploader<PaperUpdateResult, PaperUpdateError, PaperUpdateErrorException> {

    /**
     * Creates a new instance of this uploader.
     *
     * @param httpUploader  Initiated HTTP upload request
     *
     * @throws NullPointerException  if {@code httpUploader} is {@code null}
     */
    public PaperUpdateUploader(HttpRequestor.Uploader httpUploader, String userId) {
        super(httpUploader, PaperUpdateResult.Serializer.INSTANCE, PaperUpdateError.Serializer.INSTANCE, userId);
    }

    protected PaperUpdateErrorException newException(DbxWrappedException error) {
        return new PaperUpdateErrorException("2/files/paper/update", error.getRequestId(), error.getUserMessage(), (PaperUpdateError) error.getErrorValue());
    }
}
