/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.files;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link SaveUrlError} error.
 *
 * <p> This exception is raised by {@link
 * DbxUserFilesRequests#saveUrl(String,String)}. </p>
 */
public class SaveUrlErrorException extends DbxApiException {
    // exception for routes:
    //     2/files/save_url

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link
     * DbxUserFilesRequests#saveUrl(String,String)}.
     */
    public final SaveUrlError errorValue;

    public SaveUrlErrorException(String routeName, String requestId, LocalizedText userMessage, SaveUrlError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
