/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.files;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link SearchError} error.
 *
 * <p> This exception is raised by {@link
 * DbxUserFilesRequests#search(String,String)}, {@link
 * DbxUserFilesRequests#searchV2(String)}, and {@link
 * DbxUserFilesRequests#searchContinueV2(String)}. </p>
 */
public class SearchErrorException extends DbxApiException {
    // exception for routes:
    //     2/files/search
    //     2/files/search_v2
    //     2/files/search/continue_v2

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link DbxUserFilesRequests#search(String,String)},
     * {@link DbxUserFilesRequests#searchV2(String)}, and {@link
     * DbxUserFilesRequests#searchContinueV2(String)}.
     */
    public final SearchError errorValue;

    public SearchErrorException(String routeName, String requestId, LocalizedText userMessage, SearchError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
