/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.files;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link
 * UploadSessionStartError} error.
 *
 * <p> This exception is raised by {@link
 * DbxUserFilesRequests#uploadSessionStart}. </p>
 */
public class UploadSessionStartErrorException extends DbxApiException {
    // exception for routes:
    //     2/files/upload_session/start

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link DbxUserFilesRequests#uploadSessionStart}.
     */
    public final UploadSessionStartError errorValue;

    public UploadSessionStartErrorException(String routeName, String requestId, LocalizedText userMessage, UploadSessionStartError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
