/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.files;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link RemoveTagError}
 * error.
 *
 * <p> This exception is raised by {@link
 * DbxUserFilesRequests#tagsRemove(String,String)}. </p>
 */
public class RemoveTagErrorException extends DbxApiException {
    // exception for routes:
    //     2/files/tags/remove

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link
     * DbxUserFilesRequests#tagsRemove(String,String)}.
     */
    public final RemoveTagError errorValue;

    public RemoveTagErrorException(String routeName, String requestId, LocalizedText userMessage, RemoveTagError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
