/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.team;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link CustomQuotaError}
 * error.
 *
 * <p> This exception is raised by {@link
 * DbxTeamTeamRequests#memberSpaceLimitsGetCustomQuota(java.util.List)} and
 * {@link
 * DbxTeamTeamRequests#memberSpaceLimitsRemoveCustomQuota(java.util.List)}. </p>
 */
public class CustomQuotaErrorException extends DbxApiException {
    // exception for routes:
    //     2/team/member_space_limits/get_custom_quota
    //     2/team/member_space_limits/remove_custom_quota

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link
     * DbxTeamTeamRequests#memberSpaceLimitsGetCustomQuota(java.util.List)} and
     * {@link
     * DbxTeamTeamRequests#memberSpaceLimitsRemoveCustomQuota(java.util.List)}.
     */
    public final CustomQuotaError errorValue;

    public CustomQuotaErrorException(String routeName, String requestId, LocalizedText userMessage, CustomQuotaError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
