/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.team;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link
 * ExcludedUsersListError} error.
 *
 * <p> This exception is raised by {@link
 * DbxTeamTeamRequests#memberSpaceLimitsExcludedUsersList(long)}. </p>
 */
public class ExcludedUsersListErrorException extends DbxApiException {
    // exception for routes:
    //     2/team/member_space_limits/excluded_users/list

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link
     * DbxTeamTeamRequests#memberSpaceLimitsExcludedUsersList(long)}.
     */
    public final ExcludedUsersListError errorValue;

    public ExcludedUsersListErrorException(String routeName, String requestId, LocalizedText userMessage, ExcludedUsersListError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
