/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.team;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link
 * ListMembersDevicesError} error.
 *
 * <p> This exception is raised by {@link
 * DbxTeamTeamRequests#devicesListMembersDevices}. </p>
 */
public class ListMembersDevicesErrorException extends DbxApiException {
    // exception for routes:
    //     2/team/devices/list_members_devices

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link
     * DbxTeamTeamRequests#devicesListMembersDevices}.
     */
    public final ListMembersDevicesError errorValue;

    public ListMembersDevicesErrorException(String routeName, String requestId, LocalizedText userMessage, ListMembersDevicesError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
