/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.team;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link
 * MembersTransferFormerMembersFilesError} error.
 *
 * <p> This exception is raised by {@link
 * DbxTeamTeamRequests#membersMoveFormerMemberFiles(UserSelectorArg,UserSelectorArg,UserSelectorArg)}.
 * </p>
 */
public class MembersTransferFormerMembersFilesErrorException extends DbxApiException {
    // exception for routes:
    //     2/team/members/move_former_member_files

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link
     * DbxTeamTeamRequests#membersMoveFormerMemberFiles(UserSelectorArg,UserSelectorArg,UserSelectorArg)}.
     */
    public final MembersTransferFormerMembersFilesError errorValue;

    public MembersTransferFormerMembersFilesErrorException(String routeName, String requestId, LocalizedText userMessage, MembersTransferFormerMembersFilesError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
