/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.team;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link RevokeLinkedAppError}
 * error.
 *
 * <p> This exception is raised by {@link
 * DbxTeamTeamRequests#linkedAppsRevokeLinkedApp(String,String,boolean)}. </p>
 */
public class RevokeLinkedAppErrorException extends DbxApiException {
    // exception for routes:
    //     2/team/linked_apps/revoke_linked_app

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link
     * DbxTeamTeamRequests#linkedAppsRevokeLinkedApp(String,String,boolean)}.
     */
    public final RevokeLinkedAppError errorValue;

    public RevokeLinkedAppErrorException(String routeName, String requestId, LocalizedText userMessage, RevokeLinkedAppError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
