/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.team;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link SetCustomQuotaError}
 * error.
 *
 * <p> This exception is raised by {@link
 * DbxTeamTeamRequests#memberSpaceLimitsSetCustomQuota(java.util.List)}. </p>
 */
public class SetCustomQuotaErrorException extends DbxApiException {
    // exception for routes:
    //     2/team/member_space_limits/set_custom_quota

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link
     * DbxTeamTeamRequests#memberSpaceLimitsSetCustomQuota(java.util.List)}.
     */
    public final SetCustomQuotaError errorValue;

    public SetCustomQuotaErrorException(String routeName, String requestId, LocalizedText userMessage, SetCustomQuotaError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
