/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.sharing;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link
 * ListFoldersContinueError} error.
 *
 * <p> This exception is raised by {@link
 * DbxUserSharingRequests#listFoldersContinue(String)} and {@link
 * DbxUserSharingRequests#listMountableFoldersContinue(String)}. </p>
 */
public class ListFoldersContinueErrorException extends DbxApiException {
    // exception for routes:
    //     2/sharing/list_folders/continue
    //     2/sharing/list_mountable_folders/continue

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link
     * DbxUserSharingRequests#listFoldersContinue(String)} and {@link
     * DbxUserSharingRequests#listMountableFoldersContinue(String)}.
     */
    public final ListFoldersContinueError errorValue;

    public ListFoldersContinueErrorException(String routeName, String requestId, LocalizedText userMessage, ListFoldersContinueError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
