/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.sharing;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link
 * RelinquishFileMembershipError} error.
 *
 * <p> This exception is raised by {@link
 * DbxUserSharingRequests#relinquishFileMembership(String)}. </p>
 */
public class RelinquishFileMembershipErrorException extends DbxApiException {
    // exception for routes:
    //     2/sharing/relinquish_file_membership

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link
     * DbxUserSharingRequests#relinquishFileMembership(String)}.
     */
    public final RelinquishFileMembershipError errorValue;

    public RelinquishFileMembershipErrorException(String routeName, String requestId, LocalizedText userMessage, RelinquishFileMembershipError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
