/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.sharing;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link SharingUserError}
 * error.
 *
 * <p> This exception is raised by {@link
 * DbxUserSharingRequests#getFileMetadataBatch(java.util.List,java.util.List)},
 * {@link DbxUserSharingRequests#listFileMembersBatch(java.util.List,long)}, and
 * {@link DbxUserSharingRequests#listReceivedFiles}. </p>
 */
public class SharingUserErrorException extends DbxApiException {
    // exception for routes:
    //     2/sharing/get_file_metadata/batch
    //     2/sharing/list_file_members/batch
    //     2/sharing/list_received_files

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link
     * DbxUserSharingRequests#getFileMetadataBatch(java.util.List,java.util.List)},
     * {@link DbxUserSharingRequests#listFileMembersBatch(java.util.List,long)},
     * and {@link DbxUserSharingRequests#listReceivedFiles}.
     */
    public final SharingUserError errorValue;

    public SharingUserErrorException(String routeName, String requestId, LocalizedText userMessage, SharingUserError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
