/* DO NOT EDIT */
/* This file was generated by Stone */

package com.dropbox.core.v2.sharing;

import com.dropbox.core.DbxApiException;
import com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link
 * UpdateFolderPolicyError} error.
 *
 * <p> This exception is raised by {@link
 * DbxUserSharingRequests#updateFolderPolicy(String)}. </p>
 */
public class UpdateFolderPolicyErrorException extends DbxApiException {
    // exception for routes:
    //     2/sharing/update_folder_policy

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link
     * DbxUserSharingRequests#updateFolderPolicy(String)}.
     */
    public final UpdateFolderPolicyError errorValue;

    public UpdateFolderPolicyErrorException(String routeName, String requestId, LocalizedText userMessage, UpdateFolderPolicyError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
