# This workflow will build the project with Gradle and run examples
# Because secrets are not available on external forks, this job is expected to fail
# on external pull requests.

name: Build project & run examples

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'zulu'
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '2.7'
    - run: python -m pip install ply && pip install six
    - name: Grant execute permissions
      run: chmod +x gradlew && chmod +x update-submodules
            && chmod +x generate-ci-auth-file && chmod +x scripts/run-examples
    - name: Set up submodules
      run: ./update-submodules
    - name: Install new gradle build
      run: ./gradlew install
    - name: Obtain access token
      env:
        APP_KEY: ${{ secrets.APP_KEY }}
        APP_SECRET: ${{ secrets.APP_SECRET }}
        REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
      run: ./generate-ci-auth-file
    - name: Run examples
      run: ./scripts/run-examples $(find `pwd` -name auth_output)
